#!/usr/bin/env python

'''
Command line tool based on Python 3.

Functionality:
(1) Pass a word, and an optional dictionary (list of words)
(2) Obtain a rhyming word from that dictioanry
    or from a default one.

To use as a command line tool: 
1) chmod +x siri
2) export PATH=$PATH:$(pwd)

Example:
$ siri --dictionary a b c --word a
a rhymes with a
$ siri --word Disputing
Computing rhymes with Disputing

author: Todor Davchev
date: 29.04.2018
'''
import sys
import argparse
from apps import Siri

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--test', type=bool, default=False,
                        help='the word to rhyme')
    parser.add_argument('--word', default="Disputing",
                        help='the word to rhyme')
    parser.add_argument('--dictionary', nargs='*',
                        default=["Computing", "Polluting", "Diluting", "Commuting", "Recruiting", "Drooping"],
                        help='the dictionary passed')
    parser.add_argument('--filename', default='',
                        help='in case we want to load a dictionary from a txt file')
    args = parser.parse_args()

    # load dictionary from list or file
    solution = Siri(args.dictionary) if len(args.filename) == 0 else Siri(args.filename)
    if args.test:
        solution.test()
        return "Success."

    return "%s rhymes with %s." %(solution.findRhyme(args.word), args.word)

if __name__ == "__main__":
    print(main())
